# Generated by Django 5.2 on 2025-12-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='is_done',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.IntegerField(
                choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], db_index=True, default=2),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(
                fields=['-priority', 'deadline'], name='tasks_task_priorit_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(
                fields=['project', 'is_done'], name='tasks_task_project_idx'),
        ),
    ]
